package com.tempoagora.domain.entity


internal data class DataComponent(
    val appTemp: Double,
    val aqi: Int,
    val cityName: String,
    val clouds: Int,
    val countryCode: String,
    val datetime: String,
    val dewpt: Double,
    val dhi: Int,
    val dni: Int,
    val elevAngle: Int,
    val ghi: Double,
    val gust: Int,
    val hAngle: Int,
    val lat: Double,
    val lon: Double,
    val obTime: String,
    val pod: String,
    val precip: Int,
    val pres: Double,
    val rh: Int,
    val slp: Double,
    val solarRad: Int,
    val sources: List<String>,
    val stateCode: String,
    val station: String,
    val sunrise: String,
    val sunset: String,
    val temp: Double,
    val timezone: String,
    val ts: Int,
    val uv: Int,
    val vis: Int,
    val weather: WeatherLocalComponent,
    val windCdir: String,
    val windCdirFull: String,
    val windDir: Int,
    val windSpd: Double
)
