package com.tempoagora.domain.entity


internal data class DataComponent(
    val appTemp: Double,
    val aqi: Double,
    val cityName: String,
    val clouds: Double,
    val countryCode: String,
    val datetime: String,
    val dewpt: Double,
    val dhi: Double,
    val dni: Double,
    val elevAngle: Double,
    val ghi: Double,
    val gust: Double,
    val hAngle: Double,
    val lat: Double,
    val lon: Double,
    val obTime: String,
    val pod: String,
    val precip: Double,
    val pres: Double,
    val rh: Double,
    val slp: Double,
    val solarRad: Double,
    val sources: List<String>,
    val stateCode: String,
    val station: String,
    val sunrise: String,
    val sunset: String,
    val temp: Double,
    val timezone: String,
    val ts: Double,
    val uv: Double,
    val vis: Double,
    val weather: WeatherLocalComponent,
    val windCdir: String,
    val windCdirFull: String,
    val windDir: Double,
    val windSpd: Double
)
